# Dependabot configuration: update Maven, npm and Python (pip) weekly
version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/apps/core-api/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/apps/web-dashboard/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/apps/ai-worker/"
    schedule:
      interval: "weekly"
