package com.orderpilot.domain.intake;
import jakarta.persistence.*; import java.time.Instant; import java.util.UUID; import org.hibernate.annotations.JdbcTypeCode; import org.hibernate.type.SqlTypes;
@Entity @Table(name="webhook_event")
public class WebhookEvent {
  @Id @GeneratedValue private UUID id; @Column(name="tenant_id", nullable=false) private UUID tenantId; @Column(nullable=false) private String provider; @Column(name="external_event_id") private String externalEventId; @Column(name="event_type") private String eventType; @Column(name="fingerprint_sha256") private String fingerprintSha256; @Column(name="raw_payload_storage_key") private String rawPayloadStorageKey; @Column(name="signature_verified",nullable=false) private boolean signatureVerified; @Column(name="replay_detected",nullable=false) private boolean replayDetected; @JdbcTypeCode(SqlTypes.JSON) @Column(name="raw_payload",nullable=false,columnDefinition="jsonb") private String rawPayload; @JdbcTypeCode(SqlTypes.JSON) @Column(columnDefinition="jsonb") private String headers; @Column(nullable=false) private String status; @Column(name="received_at",nullable=false) private Instant receivedAt; @Column(name="created_at",nullable=false) private Instant createdAt;
  protected WebhookEvent() {}
  public WebhookEvent(UUID tenantId, String provider, String externalEventId, boolean signatureVerified, boolean replayDetected, String rawPayload, String headers, String status, Instant now){this.tenantId=tenantId; this.provider=provider; this.externalEventId=externalEventId; this.signatureVerified=signatureVerified; this.replayDetected=replayDetected; this.rawPayload=rawPayload == null || rawPayload.isBlank() ? "{}" : rawPayload; this.headers=headers; this.status=status; this.receivedAt=now; this.createdAt=now;}
  public WebhookEvent(UUID tenantId, String provider, String externalEventId, String eventType, String fingerprintSha256, String rawPayloadStorageKey, boolean signatureVerified, boolean replayDetected, String rawPayload, String headers, String status, Instant now){this(tenantId, provider, externalEventId, signatureVerified, replayDetected, rawPayload, headers, status, now); this.eventType=eventType; this.fingerprintSha256=fingerprintSha256; this.rawPayloadStorageKey=rawPayloadStorageKey;}
  public UUID getId(){return id;} public UUID getTenantId(){return tenantId;} public String getProvider(){return provider;} public String getExternalEventId(){return externalEventId;} public String getEventType(){return eventType;} public String getFingerprintSha256(){return fingerprintSha256;} public String getRawPayloadStorageKey(){return rawPayloadStorageKey;} public boolean isSignatureVerified(){return signatureVerified;} public boolean isReplayDetected(){return replayDetected;} public String getStatus(){return status;} public Instant getReceivedAt(){return receivedAt;}
}
