-- P1-E2B-02 Durable backup artifact authority and deployment-global lifecycle audit.
--
-- This migration is additive. It does not execute backups, store backup bytes, store plaintext
-- archive content, introduce restore/upgrade/rollback lifecycle types, or expose filesystem
-- authority. PostgreSQL rows are the authority for artifact state; filesystem presence alone is not.

CREATE TABLE backup_artifact (
  id                            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  public_handle                 VARCHAR(48) NOT NULL,
  lifecycle_operation_id        UUID NOT NULL,
  state                         VARCHAR(20) NOT NULL,
  backup_format                 VARCHAR(40) NOT NULL,
  encryption_algorithm          VARCHAR(40) NULL,
  encryption_envelope_version   VARCHAR(40) NULL,
  encryption_key_identifier     VARCHAR(80) NULL,
  created_at                    TIMESTAMPTZ NOT NULL,
  updated_at                    TIMESTAMPTZ NOT NULL,
  available_at                  TIMESTAMPTZ NULL,
  postgres_server_version       VARCHAR(80) NULL,
  pg_dump_version               VARCHAR(80) NULL,
  pg_restore_version            VARCHAR(80) NULL,
  schema_version                VARCHAR(40) NULL,
  encrypted_byte_size           BIGINT NULL,
  ciphertext_sha256             VARCHAR(64) NULL,
  archive_validated             BOOLEAN NULL,
  archive_entry_count           INTEGER NULL,
  storage_key                   VARCHAR(256) NOT NULL,
  execution_attempt             INTEGER NULL,
  fencing_token                 BIGINT NULL,
  failure_code                  VARCHAR(80) NULL,
  CONSTRAINT fk_backup_artifact_lifecycle_operation
    FOREIGN KEY (lifecycle_operation_id) REFERENCES lifecycle_operation(id),
  CONSTRAINT ck_backup_artifact_state
    CHECK (state IN ('STAGED', 'AVAILABLE', 'REJECTED', 'ORPHANED')),
  CONSTRAINT ck_backup_artifact_public_handle CHECK (
    public_handle ~ '^ba_[0-9a-f]{24}$'
  ),
  CONSTRAINT ck_backup_artifact_format CHECK (
    backup_format = 'POSTGRES_CUSTOM'
  ),
  CONSTRAINT ck_backup_artifact_time_order CHECK (updated_at >= created_at),
  CONSTRAINT ck_backup_artifact_available_time CHECK (
    (state = 'AVAILABLE' AND available_at IS NOT NULL AND available_at >= created_at)
    OR
    (state <> 'AVAILABLE' AND available_at IS NULL)
  ),
  CONSTRAINT ck_backup_artifact_encrypted_size CHECK (
    encrypted_byte_size IS NULL OR encrypted_byte_size >= 0
  ),
  CONSTRAINT ck_backup_artifact_archive_entry_count CHECK (
    archive_entry_count IS NULL OR archive_entry_count >= 0
  ),
  CONSTRAINT ck_backup_artifact_ciphertext_sha256 CHECK (
    ciphertext_sha256 IS NULL OR ciphertext_sha256 ~ '^[0-9a-f]{64}$'
  ),
  CONSTRAINT ck_backup_artifact_failure_code CHECK (
    failure_code IS NULL OR failure_code ~ '^[A-Z0-9_:-]{1,80}$'
  ),
  CONSTRAINT ck_backup_artifact_storage_key CHECK (
    length(storage_key) BETWEEN 1 AND 256
    AND storage_key !~ '(^/|^[A-Za-z]:|\\\\|(^|/)\\.\\.(/|$))'
  ),
  CONSTRAINT ck_backup_artifact_available_metadata CHECK (
    state <> 'AVAILABLE'
    OR
    (
      encrypted_byte_size > 0
      AND ciphertext_sha256 IS NOT NULL
      AND archive_validated IS TRUE
      AND length(coalesce(encryption_algorithm, '')) > 0
      AND length(coalesce(encryption_envelope_version, '')) > 0
      AND length(coalesce(encryption_key_identifier, '')) > 0
      AND length(coalesce(storage_key, '')) > 0
      AND available_at IS NOT NULL
    )
  )
);

CREATE UNIQUE INDEX ux_backup_artifact_public_handle
  ON backup_artifact (public_handle);

CREATE UNIQUE INDEX ux_backup_artifact_storage_key
  ON backup_artifact (storage_key);

CREATE UNIQUE INDEX ux_backup_artifact_one_available_per_operation
  ON backup_artifact (lifecycle_operation_id)
  WHERE state = 'AVAILABLE';

CREATE INDEX idx_backup_artifact_lifecycle_operation
  ON backup_artifact (lifecycle_operation_id);

CREATE INDEX idx_backup_artifact_state_created
  ON backup_artifact (state, created_at);

CREATE TABLE lifecycle_operation_audit (
  id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lifecycle_operation_id   UUID NOT NULL,
  backup_artifact_id       UUID NULL,
  event_type               VARCHAR(80) NOT NULL,
  principal_type           VARCHAR(30) NOT NULL,
  principal_fingerprint    VARCHAR(64) NOT NULL,
  result_code              VARCHAR(80) NULL,
  metadata                 JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at               TIMESTAMPTZ NOT NULL,
  CONSTRAINT fk_lifecycle_operation_audit_operation
    FOREIGN KEY (lifecycle_operation_id) REFERENCES lifecycle_operation(id),
  CONSTRAINT fk_lifecycle_operation_audit_artifact
    FOREIGN KEY (backup_artifact_id) REFERENCES backup_artifact(id),
  CONSTRAINT ck_lifecycle_operation_audit_event_type
    CHECK (event_type IN (
      'BACKUP_REQUESTED',
      'BACKUP_IDEMPOTENCY_REPLAYED',
      'BACKUP_LEASE_ACQUIRED',
      'BACKUP_EXECUTION_STARTED',
      'BACKUP_LEASE_LOST',
      'BACKUP_PROCESS_FAILED',
      'BACKUP_PROCESS_TIMED_OUT',
      'BACKUP_ARCHIVE_VALIDATED',
      'BACKUP_ARCHIVE_VALIDATION_FAILED',
      'BACKUP_ENCRYPTED',
      'BACKUP_ARTIFACT_STAGED',
      'BACKUP_ARTIFACT_AVAILABLE',
      'BACKUP_ARTIFACT_REJECTED',
      'BACKUP_ARTIFACT_ORPHANED',
      'BACKUP_STALE_EXECUTOR_DENIED',
      'BACKUP_SUCCEEDED',
      'BACKUP_FAILED'
    )),
  CONSTRAINT ck_lifecycle_operation_audit_principal_type
    CHECK (principal_type IN ('STAFF', 'EXECUTOR', 'SYSTEM')),
  CONSTRAINT ck_lifecycle_operation_audit_principal_fingerprint
    CHECK (principal_fingerprint ~ '^[0-9A-Za-z:_-]{1,64}$'),
  CONSTRAINT ck_lifecycle_operation_audit_result_code
    CHECK (result_code IS NULL OR result_code ~ '^[A-Z0-9_:-]{1,80}$'),
  CONSTRAINT ck_lifecycle_operation_audit_metadata_bound
    CHECK (length(metadata::text) <= 2048)
);

CREATE INDEX idx_lifecycle_operation_audit_operation_order
  ON lifecycle_operation_audit (lifecycle_operation_id, created_at, id);

CREATE INDEX idx_lifecycle_operation_audit_artifact_order
  ON lifecycle_operation_audit (backup_artifact_id, created_at, id)
  WHERE backup_artifact_id IS NOT NULL;