package com.orderpilot.domain.extraction;
import jakarta.persistence.*; import java.math.BigDecimal; import java.time.Instant; import java.util.UUID;
@Entity @Table(name="extracted_field")
public class ExtractedField {
  @Id @GeneratedValue private UUID id; @Column(name="tenant_id",nullable=false) private UUID tenantId; @Column(name="extraction_result_id",nullable=false) private UUID extractionResultId; @Column(name="field_name",nullable=false) private String fieldName; @Column(name="raw_value") private String rawValue; @Column(name="normalized_value") private String normalizedValue; @Column(name="value_type",nullable=false) private String valueType; @Column(nullable=false) private BigDecimal confidence; @Column(name="source_evidence_id") private UUID sourceEvidenceId; @Column(name="validation_status",nullable=false) private String validationStatus; @Column(name="created_at",nullable=false) private Instant createdAt; @Column(name="updated_at",nullable=false) private Instant updatedAt;
  protected ExtractedField() {}
  public ExtractedField(UUID tenantId, UUID extractionResultId, String fieldName, String rawValue, String normalizedValue, String valueType, BigDecimal confidence, UUID sourceEvidenceId, Instant now){this.tenantId=tenantId; this.extractionResultId=extractionResultId; this.fieldName=fieldName; this.rawValue=rawValue; this.normalizedValue=normalizedValue; this.valueType=valueType; this.confidence=confidence; this.sourceEvidenceId=sourceEvidenceId; this.validationStatus="SCHEMA_VALID"; this.createdAt=now; this.updatedAt=now;}
  public void setValidationStatus(String status, Instant now){this.validationStatus=status; this.updatedAt=now;} public UUID getId(){return id;} public UUID getTenantId(){return tenantId;} public UUID getExtractionResultId(){return extractionResultId;} public String getFieldName(){return fieldName;} public String getRawValue(){return rawValue;} public String getNormalizedValue(){return normalizedValue;} public BigDecimal getConfidence(){return confidence;} public String getValidationStatus(){return validationStatus;}
}
