package com.orderpilot.domain.extraction;
import jakarta.persistence.*; import java.math.BigDecimal; import java.time.*; import java.util.UUID;
@Entity @Table(name="extracted_line_item")
public class ExtractedLineItem {
  @Id @GeneratedValue private UUID id; @Column(name="tenant_id",nullable=false) private UUID tenantId; @Column(name="extraction_result_id",nullable=false) private UUID extractionResultId; @Column(name="line_number",nullable=false) private int lineNumber; @Column(name="raw_sku") private String rawSku; @Column(name="raw_description") private String rawDescription; @Column(name="raw_quantity") private String rawQuantity; @Column(name="normalized_quantity") private BigDecimal normalizedQuantity; @Column(name="raw_uom") private String rawUom; @Column(name="normalized_uom") private String normalizedUom; @Column(name="requested_date") private LocalDate requestedDate; @Column(name="raw_unit_price") private String rawUnitPrice; private String currency; @Column(nullable=false) private BigDecimal confidence; @Column(name="source_evidence_id") private UUID sourceEvidenceId; @Column(name="validation_status",nullable=false) private String validationStatus; @Column(name="created_at",nullable=false) private Instant createdAt; @Column(name="updated_at",nullable=false) private Instant updatedAt;
  protected ExtractedLineItem() {}
  public ExtractedLineItem(UUID tenantId, UUID extractionResultId, int lineNumber, String rawSku, String rawDescription, String rawQuantity, BigDecimal normalizedQuantity, String rawUom, String normalizedUom, BigDecimal confidence, UUID sourceEvidenceId, Instant now){this.tenantId=tenantId; this.extractionResultId=extractionResultId; this.lineNumber=lineNumber; this.rawSku=rawSku; this.rawDescription=rawDescription; this.rawQuantity=rawQuantity; this.normalizedQuantity=normalizedQuantity; this.rawUom=rawUom; this.normalizedUom=normalizedUom; this.confidence=confidence; this.sourceEvidenceId=sourceEvidenceId; this.validationStatus="SCHEMA_VALID"; this.createdAt=now; this.updatedAt=now;}
  public void setValidationStatus(String status, Instant now){this.validationStatus=status; this.updatedAt=now;} public UUID getId(){return id;} public UUID getTenantId(){return tenantId;} public UUID getExtractionResultId(){return extractionResultId;} public int getLineNumber(){return lineNumber;} public String getRawSku(){return rawSku;} public String getRawDescription(){return rawDescription;} public String getRawQuantity(){return rawQuantity;} public BigDecimal getNormalizedQuantity(){return normalizedQuantity;} public String getRawUom(){return rawUom;} public String getNormalizedUom(){return normalizedUom;} public String getRawUnitPrice(){return rawUnitPrice;} public String getCurrency(){return currency;} public BigDecimal getConfidence(){return confidence;} public String getValidationStatus(){return validationStatus;}
}
