package com.orderpilot.domain.extraction;
import jakarta.persistence.*; import java.math.BigDecimal; import java.time.Instant; import java.util.UUID; import org.hibernate.annotations.JdbcTypeCode; import org.hibernate.type.SqlTypes;
@Entity @Table(name="extraction_result")
public class ExtractionResult {
  @Id @GeneratedValue private UUID id; @Column(name="tenant_id",nullable=false) private UUID tenantId; @Column(name="extraction_run_id",nullable=false) private UUID extractionRunId; @Column(name="source_type",nullable=false) private String sourceType; @Column(name="source_id",nullable=false) private UUID sourceId; @Column(name="detected_intent",nullable=false) private String detectedIntent; @Column(name="document_type",nullable=false) private String documentType; @Column(name="overall_confidence",nullable=false) private BigDecimal overallConfidence; @JdbcTypeCode(SqlTypes.JSON) @Column(name="result_json",nullable=false,columnDefinition="jsonb") private String resultJson; @Column(name="validation_status",nullable=false) private String validationStatus; @Column(name="created_at",nullable=false) private Instant createdAt; @Column(name="updated_at",nullable=false) private Instant updatedAt;
  protected ExtractionResult() {}
  public ExtractionResult(UUID tenantId, UUID extractionRunId, String sourceType, UUID sourceId, String detectedIntent, String documentType, BigDecimal overallConfidence, String resultJson, String validationStatus, Instant now){this.tenantId=tenantId; this.extractionRunId=extractionRunId; this.sourceType=sourceType; this.sourceId=sourceId; this.detectedIntent=detectedIntent; this.documentType=documentType; this.overallConfidence=overallConfidence; this.resultJson=resultJson; this.validationStatus=validationStatus; this.createdAt=now; this.updatedAt=now;}
  public UUID getId(){return id;} public UUID getTenantId(){return tenantId;} public UUID getExtractionRunId(){return extractionRunId;} public String getSourceType(){return sourceType;} public UUID getSourceId(){return sourceId;} public String getDetectedIntent(){return detectedIntent;} public String getDocumentType(){return documentType;} public BigDecimal getOverallConfidence(){return overallConfidence;} public String getValidationStatus(){return validationStatus;} public String getResultJson(){return resultJson;}
}
