package com.orderpilot.application.services.runtime;

public enum AiWorkloadType {
  CHAT_INTENT,
  PRICE_REQUEST,
  AVAILABILITY_REQUEST,
  PURCHASE_LIST_EXTRACTION,
  DOCUMENT_EXTRACTION,
  PRODUCT_MATCHING,
  VALIDATION_EXPLANATION,
  DRAFT_GENERATION,
  ERP_RECONCILIATION,
  PAYMENT_RECONCILIATION,
  BULK_IMPORT,
  UNKNOWN
}
