export type NavigationItem = {
  label: string;
  href: string;
};

export const navigationItems: NavigationItem[] = [
  { label: "Investor Demo", href: "/demo" },
  { label: "Command Center", href: "/command-center" },
  { label: "Inbox", href: "/inbox" },
  { label: "Bot / Conversations", href: "/bot-conversations" },
  { label: "Bot Settings", href: "/bot-settings" },
  { label: "Upload", href: "/upload" },
  { label: "Documents", href: "/documents" },
  { label: "Messages", href: "/messages" },
  { label: "Extractions", href: "/extractions" },
  { label: "Validations", href: "/validations" },
  { label: "Validation Review", href: "/validation-review" },
  { label: "Exception Cockpit", href: "/exception-cockpit" },
  { label: "Conversion Review", href: "/conversion-review" },
  { label: "Quote Review", href: "/quote-review" },
  { label: "Draft Quote Review", href: "/workspace/draft-quotes" },
  { label: "Draft Order Review", href: "/workspace/draft-orders" },
  { label: "AI Work Assistant", href: "/ai-work" },
  { label: "Processing Jobs", href: "/processing-jobs" },
  { label: "Webhook Events", href: "/webhook-events" },
  { label: "Inbound Events", href: "/inbound-events" },
  { label: "Customers", href: "/customers" },
  { label: "Products", href: "/products" },
  { label: "Inventory", href: "/inventory" },
  { label: "Pricing", href: "/pricing" },
  { label: "Imports", href: "/imports" },
  { label: "Draft Quotes", href: "/quotes" },
  { label: "Draft Orders", href: "/orders" },
  { label: "Analytics", href: "/analytics" },
  { label: "Pilot Readiness", href: "/pilot-readiness" },
  { label: "Pilot Evidence Report", href: "/pilot-readiness/evidence-report" },
  { label: "Pilot Demo Scenarios", href: "/pilot-readiness/demo-scenarios" },
  { label: "Reconciliation", href: "/reconciliation" },
  { label: "Channels", href: "/channels" },
  { label: "Messenger Bridge", href: "/messenger-bridge" },
  { label: "RFQ Handoffs", href: "/channels/rfq-handoffs" },
  { label: "Channel Identities", href: "/channel-identities" },
  { label: "Bot Runtime", href: "/bot-runtime" },
  { label: "Integrations", href: "/integrations" },
  { label: "Sync Events", href: "/sync-events" },
  { label: "Audit", href: "/audit" },
  { label: "Audit / Security", href: "/audit-log" },
  { label: "Settings", href: "/settings" }
];
