import { DashboardShell } from "@/components/dashboard-shell";

export default function Page() {
  return (
    <DashboardShell title="Messages">
      <section className="panel table-panel">
        <table className="data-table">
          <thead><tr><th>Channel</th><th>Sender</th><th>Conversation</th><th>Status</th><th>Safety</th></tr></thead>
          <tbody>
            <tr><td>Telegram</td><td>Demo chat 450001</td><td>Generated by bot runtime</td><td>RFQ_REQUEST</td><td>Human review required</td></tr>
            <tr><td>Telegram</td><td>Demo chat 450001</td><td>Same demo conversation</td><td>UNKNOWN</td><td>Routes to handoff</td></tr>
          </tbody>
        </table>
      </section>
    </DashboardShell>
  );
}
