package com.orderpilot.domain.control;

public enum LifecycleOperationAuditEventType {
  BACKUP_REQUESTED,
  BACKUP_IDEMPOTENCY_REPLAYED,
  BACKUP_LEASE_ACQUIRED,
  BACKUP_EXECUTION_STARTED,
  BACKUP_LEASE_LOST,
  BACKUP_PROCESS_FAILED,
  BACKUP_PROCESS_TIMED_OUT,
  BACKUP_ARCHIVE_VALIDATED,
  BACKUP_ARCHIVE_VALIDATION_FAILED,
  BACKUP_ENCRYPTED,
  BACKUP_ARTIFACT_STAGED,
  BACKUP_ARTIFACT_AVAILABLE,
  BACKUP_ARTIFACT_REJECTED,
  BACKUP_ARTIFACT_ORPHANED,
  BACKUP_STALE_EXECUTOR_DENIED,
  BACKUP_SUCCEEDED,
  BACKUP_FAILED
}
