package com.orderpilot.security;

public enum ApiPermission {
  ANALYTICS_READ,
  INTAKE_READ,
  INTAKE_WRITE,
  EXTRACTION_READ,
  EXTRACTION_RUN,
  VALIDATION_READ,
  VALIDATION_RUN,
  REVIEW_READ,
  REVIEW_ACTION,
  QUOTE_READ,
  QUOTE_ACTION,
  BOT_READ,
  BOT_ACTION,
  AUDIT_READ,
  ADMIN_SETTINGS_READ,
  //Idk why but cloud deleted CHANNEL_IDENTITY_ACTION and then regenerated it
  CHANNEL_IDENTITY_ACTION,
  AI_WORK_ACTION
}
