package com.orderpilot.domain.integration;

public enum CompensationReasonCode {
  EXTERNAL_WRITE_NOT_EXECUTED,
  EXTERNAL_WRITE_PARTIALLY_EXECUTED,
  EXTERNAL_WRITE_FAILED_AFTER_LOCAL_STATE,
  EXTERNAL_TIMEOUT_UNKNOWN_STATE,
  VALIDATION_FAILED_BEFORE_EXECUTION,
  APPROVAL_REVOKED,
  TENANT_POLICY_BLOCKED,
  MANUAL_REVIEW_REQUESTED
}
