package com.orderpilot.domain.integration;

public enum ConnectorCommandExecutionState {
  NOT_REQUESTED,
  REQUESTED,
  APPROVED,
  EXECUTION_BLOCKED,
  EXECUTION_READY,
  EXECUTED,
  EXECUTION_FAILED,
  COMPENSATION_REQUIRED,
  COMPENSATION_PLANNED,
  COMPENSATED,
  COMPENSATION_FAILED,
  MANUAL_REVIEW_REQUIRED
}
