package com.orderpilot.domain.validation;

import jakarta.persistence.*; import java.math.BigDecimal; import java.time.Instant; import java.util.UUID;
@Entity @Table(name = "inventory_check_result")
public class InventoryCheckResult {
  @Id @GeneratedValue private UUID id; @Column(name="tenant_id",nullable=false) private UUID tenantId; @Column(name="validation_run_id",nullable=false) private UUID validationRunId; @Column(name="extracted_line_item_id",nullable=false) private UUID extractedLineItemId; @Column(name="product_id") private UUID productId; @Column(name="location_id") private UUID locationId; @Column(name="requested_quantity") private BigDecimal requestedQuantity; @Column(name="quantity_on_hand") private BigDecimal quantityOnHand; @Column(name="quantity_available") private BigDecimal quantityAvailable; @Column(name="quantity_reserved") private BigDecimal quantityReserved; @Column(nullable=false) private String status; @Column(name="snapshot_id") private UUID snapshotId; @Column(name="checked_at",nullable=false) private Instant checkedAt; @Column(name="created_at",nullable=false) private Instant createdAt; @Column(name="updated_at",nullable=false) private Instant updatedAt;
  protected InventoryCheckResult() {}
  public InventoryCheckResult(UUID tenantId, UUID validationRunId, UUID lineId, UUID productId, UUID locationId, BigDecimal requestedQuantity, BigDecimal onHand, BigDecimal available, BigDecimal reserved, String status, UUID snapshotId, Instant now){this.tenantId=tenantId;this.validationRunId=validationRunId;this.extractedLineItemId=lineId;this.productId=productId;this.locationId=locationId;this.requestedQuantity=requestedQuantity;this.quantityOnHand=onHand;this.quantityAvailable=available;this.quantityReserved=reserved;this.status=status;this.snapshotId=snapshotId;this.checkedAt=now;this.createdAt=now;this.updatedAt=now;}
  public UUID getId(){return id;} public UUID getExtractedLineItemId(){return extractedLineItemId;} public UUID getProductId(){return productId;} public UUID getLocationId(){return locationId;} public BigDecimal getRequestedQuantity(){return requestedQuantity;} public BigDecimal getQuantityAvailable(){return quantityAvailable;} public String getStatus(){return status;} public UUID getSnapshotId(){return snapshotId;}
}
