package com.orderpilot.domain.validation;

import jakarta.persistence.*; import java.math.BigDecimal; import java.time.Instant; import java.util.UUID;
@Entity @Table(name = "margin_check_result")
public class MarginCheckResult {
  @Id @GeneratedValue private UUID id; @Column(name="tenant_id",nullable=false) private UUID tenantId; @Column(name="validation_run_id",nullable=false) private UUID validationRunId; @Column(name="extracted_line_item_id",nullable=false) private UUID extractedLineItemId; @Column(name="product_id") private UUID productId; @Column(name="margin_rule_id") private UUID marginRuleId; @Column(name="unit_price") private BigDecimal unitPrice; @Column(name="unit_cost") private BigDecimal unitCost; @Column(name="gross_margin_percent") private BigDecimal grossMarginPercent; @Column(name="minimum_gross_margin_percent") private BigDecimal minimumGrossMarginPercent; @Column(name="approval_required_below_percent") private BigDecimal approvalRequiredBelowPercent; @Column(name="requires_approval",nullable=false) private boolean requiresApproval; @Column(nullable=false) private String status; @Column(name="created_at",nullable=false) private Instant createdAt; @Column(name="updated_at",nullable=false) private Instant updatedAt;
  protected MarginCheckResult() {}
  public MarginCheckResult(UUID tenantId, UUID validationRunId, UUID lineId, UUID productId, UUID ruleId, BigDecimal unitPrice, BigDecimal unitCost, BigDecimal grossMargin, BigDecimal minimum, BigDecimal approvalBelow, boolean requiresApproval, String status, Instant now){this.tenantId=tenantId;this.validationRunId=validationRunId;this.extractedLineItemId=lineId;this.productId=productId;this.marginRuleId=ruleId;this.unitPrice=unitPrice;this.unitCost=unitCost;this.grossMarginPercent=grossMargin;this.minimumGrossMarginPercent=minimum;this.approvalRequiredBelowPercent=approvalBelow;this.requiresApproval=requiresApproval;this.status=status;this.createdAt=now;this.updatedAt=now;}
  public UUID getId(){return id;} public UUID getExtractedLineItemId(){return extractedLineItemId;} public UUID getProductId(){return productId;} public BigDecimal getUnitPrice(){return unitPrice;} public BigDecimal getUnitCost(){return unitCost;} public BigDecimal getGrossMarginPercent(){return grossMarginPercent;} public boolean isRequiresApproval(){return requiresApproval;} public String getStatus(){return status;}
}
