package com.orderpilot.domain.validation;

import jakarta.persistence.*; import java.math.BigDecimal; import java.time.Instant; import java.util.UUID; import org.hibernate.annotations.JdbcTypeCode; import org.hibernate.type.SqlTypes;
@Entity @Table(name = "product_match_result")
public class ProductMatchResult {
  @Id @GeneratedValue private UUID id; @Column(name="tenant_id",nullable=false) private UUID tenantId; @Column(name="validation_run_id",nullable=false) private UUID validationRunId; @Column(name="extracted_line_item_id",nullable=false) private UUID extractedLineItemId; @Column(name="matched_product_id") private UUID matchedProductId; @Column(name="raw_sku") private String rawSku; @Column(name="raw_description") private String rawDescription; @Column(name="match_type",nullable=false) private String matchType; @Column(nullable=false) private BigDecimal confidence; @Column(nullable=false) private String status; @JdbcTypeCode(SqlTypes.JSON) @Column(name="candidates_json",columnDefinition="jsonb") private String candidatesJson; @Column(name="created_at",nullable=false) private Instant createdAt; @Column(name="updated_at",nullable=false) private Instant updatedAt;
  protected ProductMatchResult() {}
  public ProductMatchResult(UUID tenantId, UUID validationRunId, UUID lineId, UUID productId, String rawSku, String rawDescription, String matchType, BigDecimal confidence, String status, String candidatesJson, Instant now){this.tenantId=tenantId;this.validationRunId=validationRunId;this.extractedLineItemId=lineId;this.matchedProductId=productId;this.rawSku=rawSku;this.rawDescription=rawDescription;this.matchType=matchType;this.confidence=confidence;this.status=status;this.candidatesJson=candidatesJson;this.createdAt=now;this.updatedAt=now;}
  public void confirmMatch(UUID productId, String matchType, Instant now){this.matchedProductId=productId;this.matchType=matchType;this.status="MATCHED";this.confidence=BigDecimal.ONE;this.updatedAt=now;} public UUID getId(){return id;} public UUID getExtractedLineItemId(){return extractedLineItemId;} public UUID getMatchedProductId(){return matchedProductId;} public String getRawSku(){return rawSku;} public String getRawDescription(){return rawDescription;} public String getMatchType(){return matchType;} public BigDecimal getConfidence(){return confidence;} public String getStatus(){return status;} public String getCandidatesJson(){return candidatesJson;}
}
