package com.orderpilot.domain.validation;

import jakarta.persistence.*; import java.math.BigDecimal; import java.time.Instant; import java.util.UUID;
@Entity @Table(name = "substitute_candidate")
public class SubstituteCandidate {
  @Id @GeneratedValue private UUID id; @Column(name="tenant_id",nullable=false) private UUID tenantId; @Column(name="validation_run_id",nullable=false) private UUID validationRunId; @Column(name="extracted_line_item_id",nullable=false) private UUID extractedLineItemId; @Column(name="source_product_id") private UUID sourceProductId; @Column(name="substitute_product_id",nullable=false) private UUID substituteProductId; @Column(name="substitute_type",nullable=false) private String substituteType; @Column(name="risk_level",nullable=false) private String riskLevel; @Column(name="rank_score",nullable=false) private BigDecimal rankScore; @Column(nullable=false) private String reason; @Column(name="inventory_status") private String inventoryStatus; @Column(name="margin_status") private String marginStatus; @Column(name="requires_approval",nullable=false) private boolean requiresApproval; @Column(nullable=false) private String status; @Column(name="created_at",nullable=false) private Instant createdAt; @Column(name="updated_at",nullable=false) private Instant updatedAt;
  protected SubstituteCandidate() {}
  public SubstituteCandidate(UUID tenantId, UUID validationRunId, UUID lineId, UUID sourceProductId, UUID substituteProductId, String substituteType, String riskLevel, BigDecimal rankScore, String reason, String inventoryStatus, String marginStatus, boolean requiresApproval, String status, Instant now){this.tenantId=tenantId;this.validationRunId=validationRunId;this.extractedLineItemId=lineId;this.sourceProductId=sourceProductId;this.substituteProductId=substituteProductId;this.substituteType=substituteType;this.riskLevel=riskLevel;this.rankScore=rankScore;this.reason=reason;this.inventoryStatus=inventoryStatus;this.marginStatus=marginStatus;this.requiresApproval=requiresApproval;this.status=status;this.createdAt=now;this.updatedAt=now;}
  public UUID getId(){return id;} public UUID getValidationRunId(){return validationRunId;} public UUID getExtractedLineItemId(){return extractedLineItemId;} public UUID getSourceProductId(){return sourceProductId;} public UUID getSubstituteProductId(){return substituteProductId;} public String getSubstituteType(){return substituteType;} public String getRiskLevel(){return riskLevel;} public BigDecimal getRankScore(){return rankScore;} public boolean isRequiresApproval(){return requiresApproval;} public String getStatus(){return status;}
}
