package com.orderpilot.domain.validation;

public enum ValidationIssueType {
  INVALID_QUANTITY,
  REQUESTED_DATE_INVALID,
  LOW_EXTRACTION_CONFIDENCE,
  PRODUCT_ALIAS_MATCHED,
  OEM_MATCHED,
  PRODUCT_AMBIGUOUS,
  PRODUCT_NOT_FOUND,
  INVALID_UOM,
  UOM_NORMALIZED,
  NEEDS_HUMAN_REVIEW,
  OUT_OF_STOCK,
  LOW_STOCK,
  PRICE_NOT_FOUND,
  MARGIN_BELOW_GUARDRAIL,
  SUBSTITUTE_REQUIRED,
  SUBSTITUTE_AVAILABLE
}
