package com.orderpilot.domain.workspace;

import jakarta.persistence.*; import java.math.BigDecimal; import java.time.Instant; import java.util.UUID; import org.hibernate.annotations.JdbcTypeCode; import org.hibernate.type.SqlTypes;
@Entity @Table(name="draft_quote_line")
public class DraftQuoteLine {
  @Id @GeneratedValue private UUID id; @Column(name="tenant_id",nullable=false) private UUID tenantId; @Column(name="draft_quote_id",nullable=false) private UUID draftQuoteId; @Column(name="source_extracted_line_item_id") private UUID sourceExtractedLineItemId; @Column(name="product_id") private UUID productId; @Column(name="selected_substitute_product_id") private UUID selectedSubstituteProductId; @Column(name="line_number",nullable=false) private int lineNumber; @Column(name="raw_text") private String rawText; @Column(name="raw_sku") private String rawSku; @Column(name="normalized_sku") private String normalizedSku; @Column(name="product_name") private String productName; private String description; @Column(nullable=false) private BigDecimal quantity; @Column(nullable=false) private String uom; @Column(name="requested_location") private String requestedLocation; @Column(name="unit_price") private BigDecimal unitPrice; @Column(name="discount_percent") private BigDecimal discountPercent; @Column(name="line_total") private BigDecimal lineTotal; @Column(name="available_stock") private BigDecimal availableStock; @Column(name="confidence_score") private BigDecimal confidenceScore; @JdbcTypeCode(SqlTypes.JSON) @Column(name="issue_codes", columnDefinition="jsonb") private String issueCodes; @Column(name="margin_percent") private BigDecimal marginPercent; @Column(name="substitute_decision_status",nullable=false) private String substituteDecisionStatus; @Column(name="substitute_decision_reason_code") private String substituteDecisionReasonCode; @Column(name="substitute_decided_by") private UUID substituteDecidedBy; @Column(name="substitute_decided_at") private Instant substituteDecidedAt; @Column(name="substitute_decision_note") private String substituteDecisionNote; @Column(nullable=false) private String status; @Column(name="validation_status",nullable=false) private String validationStatus; @Column(name="created_at",nullable=false) private Instant createdAt; @Column(name="updated_at",nullable=false) private Instant updatedAt;
  protected DraftQuoteLine() {}
  public DraftQuoteLine(UUID tenantId, UUID draftQuoteId, UUID lineId, UUID productId, UUID substituteId, int lineNumber, String description, BigDecimal quantity, String uom, BigDecimal unitPrice, BigDecimal discountPercent, BigDecimal marginPercent, String status, String validationStatus, Instant now){this.tenantId=tenantId;this.draftQuoteId=draftQuoteId;this.sourceExtractedLineItemId=lineId;this.productId=productId;this.selectedSubstituteProductId=substituteId;this.lineNumber=lineNumber;this.description=description;this.quantity=quantity;this.uom=uom;this.unitPrice=unitPrice;this.discountPercent=discountPercent;this.lineTotal=unitPrice==null?null:quantity.multiply(unitPrice);this.marginPercent=marginPercent;this.substituteDecisionStatus=substituteId==null?"NO_SUBSTITUTE_REQUIRED":"SUBSTITUTE_APPROVED";this.status=status;this.validationStatus=validationStatus;this.createdAt=now;this.updatedAt=now;}
  public DraftQuoteLine(UUID tenantId, UUID draftQuoteId, int lineNumber, String rawText, String rawSku, String normalizedSku, UUID productId, String productName, BigDecimal quantity, String uom, String requestedLocation, BigDecimal unitPrice, BigDecimal availableStock, BigDecimal confidenceScore, String issueCodes, String status, String validationStatus, Instant now){this.tenantId=tenantId;this.draftQuoteId=draftQuoteId;this.lineNumber=lineNumber;this.rawText=rawText;this.rawSku=rawSku;this.normalizedSku=normalizedSku;this.productId=productId;this.productName=productName;this.description=rawText;this.quantity=quantity;this.uom=uom;this.requestedLocation=requestedLocation;this.unitPrice=unitPrice;this.lineTotal=unitPrice==null?null:quantity.multiply(unitPrice);this.availableStock=availableStock;this.confidenceScore=confidenceScore;this.issueCodes=issueCodes==null||issueCodes.isBlank()?"[]":issueCodes;this.substituteDecisionStatus="NO_SUBSTITUTE_REQUIRED";this.status=status;this.validationStatus=validationStatus;this.createdAt=now;this.updatedAt=now;}
  public void setSubstituteDecision(String decisionStatus, UUID substituteProductId, String reasonCode, UUID actorId, String note, Instant now){this.substituteDecisionStatus=decisionStatus;this.selectedSubstituteProductId=substituteProductId;this.substituteDecisionReasonCode=reasonCode;this.substituteDecidedBy=actorId;this.substituteDecidedAt=now;this.substituteDecisionNote=note;this.updatedAt=now;if("SUBSTITUTE_APPROVED".equals(decisionStatus)){this.status="DRAFT";this.validationStatus="VALIDATED";}else if("SUBSTITUTE_REJECTED".equals(decisionStatus)||"SUBSTITUTE_BLOCKED".equals(decisionStatus)||"NO_SAFE_SUBSTITUTE_FOUND".equals(decisionStatus)){this.status="NEEDS_REVIEW";this.validationStatus="NEEDS_REVIEW";}}
  public void resetSubstituteDecision(Instant now){this.selectedSubstituteProductId=null;this.substituteDecisionStatus="SUBSTITUTE_SUGGESTED";this.substituteDecisionReasonCode="RESET";this.substituteDecidedBy=null;this.substituteDecidedAt=null;this.substituteDecisionNote=null;this.status="NEEDS_REVIEW";this.validationStatus="NEEDS_REVIEW";this.updatedAt=now;}
  public void markSubstituteSuggested(String decisionStatus, String reasonCode, Instant now){this.substituteDecisionStatus=decisionStatus;this.substituteDecisionReasonCode=reasonCode;this.status="NEEDS_REVIEW";this.validationStatus="NEEDS_REVIEW";this.updatedAt=now;}
  public void correctQuantity(BigDecimal quantity, Instant now){this.quantity=quantity;this.status="NEEDS_REVIEW";this.validationStatus="NEEDS_REVIEW";this.updatedAt=now;}
  public void correctUom(String uom, Instant now){this.uom=uom;this.status="NEEDS_REVIEW";this.validationStatus="NEEDS_REVIEW";this.updatedAt=now;}
  public void correctProduct(UUID productId, String productName, String normalizedSku, Instant now){this.productId=productId;this.productName=productName;this.normalizedSku=normalizedSku;this.status="NEEDS_REVIEW";this.validationStatus="NEEDS_REVIEW";this.updatedAt=now;}
  public void markManualFollowUp(String reasonCode, UUID actorId, String note, Instant now){this.substituteDecisionReasonCode=reasonCode;this.substituteDecidedBy=actorId;this.substituteDecidedAt=now;this.substituteDecisionNote=note;this.status="NEEDS_REVIEW";this.validationStatus="NEEDS_REVIEW";this.updatedAt=now;}
  public void removeFromReview(UUID actorId, String note, Instant now){this.substituteDecidedBy=actorId;this.substituteDecidedAt=now;this.substituteDecisionNote=note;this.status="REMOVED";this.validationStatus="REMOVED";this.updatedAt=now;}
  public void applyTransactionPricing(BigDecimal discountPercent, BigDecimal lineTotal, BigDecimal marginPercent, Instant now){this.discountPercent=discountPercent;this.lineTotal=lineTotal;this.marginPercent=marginPercent;this.updatedAt=now;}
  public UUID getId(){return id;} public UUID getTenantId(){return tenantId;} public UUID getDraftQuoteId(){return draftQuoteId;} public UUID getProductId(){return productId;} public UUID getSelectedSubstituteProductId(){return selectedSubstituteProductId;} public int getLineNumber(){return lineNumber;} public String getRawText(){return rawText;} public String getRawSku(){return rawSku;} public String getNormalizedSku(){return normalizedSku;} public String getProductName(){return productName;} public BigDecimal getQuantity(){return quantity;} public String getUom(){return uom;} public String getRequestedLocation(){return requestedLocation;} public BigDecimal getUnitPrice(){return unitPrice;} public BigDecimal getDiscountPercent(){return discountPercent;} public BigDecimal getLineTotal(){return lineTotal;} public BigDecimal getMarginPercent(){return marginPercent;} public BigDecimal getAvailableStock(){return availableStock;} public BigDecimal getConfidenceScore(){return confidenceScore;} public String getIssueCodes(){return issueCodes;} public String getSubstituteDecisionStatus(){return substituteDecisionStatus;} public String getSubstituteDecisionReasonCode(){return substituteDecisionReasonCode;} public UUID getSubstituteDecidedBy(){return substituteDecidedBy;} public Instant getSubstituteDecidedAt(){return substituteDecidedAt;} public String getSubstituteDecisionNote(){return substituteDecisionNote;} public String getStatus(){return status;} public String getValidationStatus(){return validationStatus;}
}
