package com.orderpilot.domain.workspace;

import jakarta.persistence.*; import java.math.BigDecimal; import java.time.Instant; import java.util.UUID;
@Entity @Table(name="draft_quote_line")
public class DraftQuoteLine {
  @Id @GeneratedValue private UUID id; @Column(name="tenant_id",nullable=false) private UUID tenantId; @Column(name="draft_quote_id",nullable=false) private UUID draftQuoteId; @Column(name="source_extracted_line_item_id") private UUID sourceExtractedLineItemId; @Column(name="product_id") private UUID productId; @Column(name="selected_substitute_product_id") private UUID selectedSubstituteProductId; @Column(name="line_number",nullable=false) private int lineNumber; private String description; @Column(nullable=false) private BigDecimal quantity; @Column(nullable=false) private String uom; @Column(name="unit_price") private BigDecimal unitPrice; @Column(name="discount_percent") private BigDecimal discountPercent; @Column(name="line_total") private BigDecimal lineTotal; @Column(name="margin_percent") private BigDecimal marginPercent; @Column(nullable=false) private String status; @Column(name="validation_status",nullable=false) private String validationStatus; @Column(name="created_at",nullable=false) private Instant createdAt; @Column(name="updated_at",nullable=false) private Instant updatedAt;
  protected DraftQuoteLine() {}
  public DraftQuoteLine(UUID tenantId, UUID draftQuoteId, UUID lineId, UUID productId, UUID substituteId, int lineNumber, String description, BigDecimal quantity, String uom, BigDecimal unitPrice, BigDecimal discountPercent, BigDecimal marginPercent, String status, String validationStatus, Instant now){this.tenantId=tenantId;this.draftQuoteId=draftQuoteId;this.sourceExtractedLineItemId=lineId;this.productId=productId;this.selectedSubstituteProductId=substituteId;this.lineNumber=lineNumber;this.description=description;this.quantity=quantity;this.uom=uom;this.unitPrice=unitPrice;this.discountPercent=discountPercent;this.lineTotal=unitPrice==null?null:quantity.multiply(unitPrice);this.marginPercent=marginPercent;this.status=status;this.validationStatus=validationStatus;this.createdAt=now;this.updatedAt=now;}
  public UUID getId(){return id;} public UUID getDraftQuoteId(){return draftQuoteId;} public UUID getProductId(){return productId;} public int getLineNumber(){return lineNumber;} public BigDecimal getLineTotal(){return lineTotal;} public String getStatus(){return status;} public String getValidationStatus(){return validationStatus;}
}
