package com.orderpilot.domain.workspace;

import jakarta.persistence.*; import java.math.BigDecimal; import java.time.*; import java.util.UUID;
@Entity @Table(name="draft_order_line")
public class DraftOrderLine {
  @Id @GeneratedValue private UUID id; @Column(name="tenant_id",nullable=false) private UUID tenantId; @Column(name="draft_order_id",nullable=false) private UUID draftOrderId; @Column(name="source_extracted_line_item_id") private UUID sourceExtractedLineItemId; @Column(name="product_id") private UUID productId; @Column(name="selected_substitute_product_id") private UUID selectedSubstituteProductId; @Column(name="line_number",nullable=false) private int lineNumber; private String description; @Column(nullable=false) private BigDecimal quantity; @Column(nullable=false) private String uom; @Column(name="unit_price") private BigDecimal unitPrice; @Column(name="discount_percent") private BigDecimal discountPercent; @Column(name="line_total") private BigDecimal lineTotal; @Column(name="margin_percent") private BigDecimal marginPercent; @Column(name="requested_date") private LocalDate requestedDate; @Column(nullable=false) private String status; @Column(name="validation_status",nullable=false) private String validationStatus; @Column(name="created_at",nullable=false) private Instant createdAt; @Column(name="updated_at",nullable=false) private Instant updatedAt;
  protected DraftOrderLine() {}
  public DraftOrderLine(UUID tenantId, UUID draftOrderId, UUID lineId, UUID productId, UUID substituteId, int lineNumber, String description, BigDecimal quantity, String uom, BigDecimal unitPrice, BigDecimal discountPercent, BigDecimal marginPercent, LocalDate requestedDate, String status, String validationStatus, Instant now){this.tenantId=tenantId;this.draftOrderId=draftOrderId;this.sourceExtractedLineItemId=lineId;this.productId=productId;this.selectedSubstituteProductId=substituteId;this.lineNumber=lineNumber;this.description=description;this.quantity=quantity;this.uom=uom;this.unitPrice=unitPrice;this.discountPercent=discountPercent;this.lineTotal=unitPrice==null?null:quantity.multiply(unitPrice);this.marginPercent=marginPercent;this.requestedDate=requestedDate;this.status=status;this.validationStatus=validationStatus;this.createdAt=now;this.updatedAt=now;}
  // OP-CAP-09B: bounded operator line correction. Applies only provided fields, recomputes line total, returns line to internal review.
  public void applyOperatorCorrection(BigDecimal quantity, String uom, String description, BigDecimal unitPrice, UUID productId, Instant now){if(quantity!=null)this.quantity=quantity;if(uom!=null)this.uom=uom;if(description!=null)this.description=description;if(unitPrice!=null)this.unitPrice=unitPrice;if(productId!=null)this.productId=productId;this.lineTotal=this.unitPrice==null?null:this.quantity.multiply(this.unitPrice);this.status="NEEDS_REVIEW";this.validationStatus="NEEDS_REVIEW";this.updatedAt=now;}
  public UUID getId(){return id;} public UUID getTenantId(){return tenantId;} public UUID getDraftOrderId(){return draftOrderId;} public UUID getProductId(){return productId;} public int getLineNumber(){return lineNumber;} public String getDescription(){return description;} public BigDecimal getQuantity(){return quantity;} public String getUom(){return uom;} public BigDecimal getUnitPrice(){return unitPrice;} public BigDecimal getDiscountPercent(){return discountPercent;} public BigDecimal getLineTotal(){return lineTotal;} public BigDecimal getMarginPercent(){return marginPercent;} public String getStatus(){return status;} public String getValidationStatus(){return validationStatus;}
}
