package com.orderpilot.domain.workspace;

import jakarta.persistence.*; import java.math.BigDecimal; import java.time.Instant; import java.util.UUID;
@Entity @Table(name="draft_quote")
public class DraftQuote {
  @Id @GeneratedValue private UUID id; @Column(name="tenant_id",nullable=false) private UUID tenantId; @Column(name="quote_number",nullable=false) private String quoteNumber; @Column(name="customer_account_id") private UUID customerAccountId; @Column(name="customer_display_name") private String customerDisplayName; @Column(name="source_type") private String sourceType; @Column(name="source_message_id") private UUID sourceMessageId; @Column(name="source_document_id") private UUID sourceDocumentId; @Column(name="source_extraction_result_id") private UUID sourceExtractionResultId; @Column(name="source_validation_run_id") private UUID sourceValidationRunId; @Column(name="source_exception_case_id") private UUID sourceExceptionCaseId; @Column(nullable=false) private String status; @Column(name="validation_status") private String validationStatus; @Column(name="requires_human_review") private boolean requiresHumanReview; private String currency; @Column(name="subtotal_amount") private BigDecimal subtotalAmount; @Column(name="discount_amount") private BigDecimal discountAmount; @Column(name="total_amount") private BigDecimal totalAmount; @Column(name="margin_percent") private BigDecimal marginPercent; private String notes; @Column(name="created_by") private UUID createdBy; @Column(name="approved_by") private UUID approvedBy; @Column(name="audit_correlation_id") private UUID auditCorrelationId; @Column(name="created_at",nullable=false) private Instant createdAt; @Column(name="updated_at",nullable=false) private Instant updatedAt; @Column(name="approved_at") private Instant approvedAt;
  protected DraftQuote() {}
  public DraftQuote(UUID tenantId, String quoteNumber, UUID customerId, UUID extractionResultId, UUID validationRunId, UUID caseId, String status, String currency, UUID createdBy, Instant now){this.tenantId=tenantId;this.quoteNumber=quoteNumber;this.customerAccountId=customerId;this.sourceExtractionResultId=extractionResultId;this.sourceValidationRunId=validationRunId;this.sourceExceptionCaseId=caseId;this.status=status;this.currency=currency;this.createdBy=createdBy;this.subtotalAmount=BigDecimal.ZERO;this.discountAmount=BigDecimal.ZERO;this.totalAmount=BigDecimal.ZERO;this.createdAt=now;this.updatedAt=now;}
  public DraftQuote(UUID tenantId, String quoteNumber, String sourceType, UUID sourceMessageId, UUID sourceDocumentId, UUID customerId, String customerDisplayName, String status, String validationStatus, boolean requiresHumanReview, String currency, UUID createdBy, UUID auditCorrelationId, Instant now){this.tenantId=tenantId;this.quoteNumber=quoteNumber;this.sourceType=sourceType;this.sourceMessageId=sourceMessageId;this.sourceDocumentId=sourceDocumentId;this.customerAccountId=customerId;this.customerDisplayName=customerDisplayName;this.status=status;this.validationStatus=validationStatus;this.requiresHumanReview=requiresHumanReview;this.currency=currency;this.createdBy=createdBy;this.auditCorrelationId=auditCorrelationId;this.subtotalAmount=BigDecimal.ZERO;this.discountAmount=BigDecimal.ZERO;this.totalAmount=BigDecimal.ZERO;this.createdAt=now;this.updatedAt=now;}
  public void setTotals(BigDecimal subtotal, BigDecimal discount, BigDecimal total, BigDecimal margin, Instant now){this.subtotalAmount=subtotal;this.discountAmount=discount;this.totalAmount=total;this.marginPercent=margin;this.updatedAt=now;} public void setStatus(String status, UUID userId, Instant now){this.status=status;this.updatedAt=now;if("APPROVED_INTERNAL".equals(status)||"APPROVED".equals(status)){this.approvedBy=userId;this.approvedAt=now;}}
  public void markValidated(String status, String validationStatus, boolean requiresHumanReview, Instant now){this.status=status;this.validationStatus=validationStatus;this.requiresHumanReview=requiresHumanReview;this.updatedAt=now;}
  public void transition(String status, String validationStatus, boolean requiresHumanReview, UUID actorId, Instant now){this.status=status;this.validationStatus=validationStatus;this.requiresHumanReview=requiresHumanReview;this.updatedAt=now;if("APPROVED".equals(status)){this.approvedBy=actorId;this.approvedAt=now;}}
  public void appendNote(String note, Instant now){if(note!=null&&!note.isBlank()){this.notes=note;this.updatedAt=now;}}
  public UUID getId(){return id;} public UUID getTenantId(){return tenantId;} public String getQuoteNumber(){return quoteNumber;} public UUID getCustomerAccountId(){return customerAccountId;} public String getCustomerDisplayName(){return customerDisplayName;} public String getSourceType(){return sourceType;} public UUID getSourceMessageId(){return sourceMessageId;} public UUID getSourceDocumentId(){return sourceDocumentId;} public UUID getSourceValidationRunId(){return sourceValidationRunId;} public String getStatus(){return status;} public String getValidationStatus(){return validationStatus;} public boolean isRequiresHumanReview(){return requiresHumanReview;} public String getCurrency(){return currency;} public BigDecimal getSubtotalAmount(){return subtotalAmount;} public BigDecimal getDiscountAmount(){return discountAmount;} public BigDecimal getTotalAmount(){return totalAmount;} public BigDecimal getMarginPercent(){return marginPercent;} public String getNotes(){return notes;} public UUID getApprovedBy(){return approvedBy;} public UUID getAuditCorrelationId(){return auditCorrelationId;} public Instant getCreatedAt(){return createdAt;} public Instant getApprovedAt(){return approvedAt;}
}
