package com.orderpilot.domain.workspace;

import jakarta.persistence.*; import java.time.Instant; import java.util.UUID;
@Entity @Table(name="exception_case")
public class ExceptionCase {
  @Id @GeneratedValue private UUID id; @Column(name="tenant_id",nullable=false) private UUID tenantId; @Column(name="case_number",nullable=false) private String caseNumber; @Column(name="source_type",nullable=false) private String sourceType; @Column(name="source_id") private UUID sourceId; @Column(name="extraction_result_id") private UUID extractionResultId; @Column(name="validation_run_id") private UUID validationRunId; @Column(name="customer_account_id") private UUID customerAccountId; @Column(nullable=false) private String title; @Column(nullable=false) private String status; @Column(nullable=false) private String priority; @Column(nullable=false) private String severity; @Column(name="assigned_to_user_id") private UUID assignedToUserId; @Column(columnDefinition="TEXT") private String summary; @Column(name="created_at",nullable=false) private Instant createdAt; @Column(name="updated_at",nullable=false) private Instant updatedAt; @Column(name="resolved_at") private Instant resolvedAt;
  protected ExceptionCase() {}
  public ExceptionCase(UUID tenantId, String caseNumber, String sourceType, UUID sourceId, UUID extractionResultId, UUID validationRunId, UUID customerAccountId, String title, String status, String priority, String severity, String summary, Instant now){this.tenantId=tenantId;this.caseNumber=caseNumber;this.sourceType=sourceType;this.sourceId=sourceId;this.extractionResultId=extractionResultId;this.validationRunId=validationRunId;this.customerAccountId=customerAccountId;this.title=title;this.status=status;this.priority=priority;this.severity=severity;this.summary=summary;this.createdAt=now;this.updatedAt=now;}
  public void assign(UUID userId, Instant now){this.assignedToUserId=userId;this.status="IN_REVIEW";this.updatedAt=now;} public void setStatus(String status, Instant now){this.status=status;this.updatedAt=now;if("RESOLVED".equals(status)||"REJECTED".equals(status)||"CANCELLED".equals(status))this.resolvedAt=now;}
  public UUID getId(){return id;} public UUID getTenantId(){return tenantId;} public String getCaseNumber(){return caseNumber;} public String getSourceType(){return sourceType;} public UUID getSourceId(){return sourceId;} public UUID getExtractionResultId(){return extractionResultId;} public UUID getValidationRunId(){return validationRunId;} public UUID getCustomerAccountId(){return customerAccountId;} public String getTitle(){return title;} public String getStatus(){return status;} public String getPriority(){return priority;} public String getSeverity(){return severity;} public UUID getAssignedToUserId(){return assignedToUserId;} public String getSummary(){return summary;} public Instant getCreatedAt(){return createdAt;} public Instant getResolvedAt(){return resolvedAt;}
}
