package com.orderpilot.domain.workspace;

import jakarta.persistence.*; import java.math.BigDecimal; import java.time.Instant; import java.util.UUID; import org.hibernate.annotations.JdbcTypeCode; import org.hibernate.type.SqlTypes;
@Entity @Table(name="suggested_fix")
public class SuggestedFix {
  @Id @GeneratedValue private UUID id; @Column(name="tenant_id",nullable=false) private UUID tenantId; @Column(name="exception_case_id") private UUID exceptionCaseId; @Column(name="validation_run_id") private UUID validationRunId; @Column(name="validation_issue_id") private UUID validationIssueId; @Column(name="extracted_line_item_id") private UUID extractedLineItemId; @Column(name="fix_type",nullable=false) private String fixType; @Column(nullable=false) private String status; @JdbcTypeCode(SqlTypes.JSON) @Column(name="suggestion_json",nullable=false,columnDefinition="jsonb") private String suggestionJson; private BigDecimal confidence; private String reason; @Column(name="created_at",nullable=false) private Instant createdAt; @Column(name="updated_at",nullable=false) private Instant updatedAt;
  protected SuggestedFix() {}
  public SuggestedFix(UUID tenantId, UUID caseId, UUID runId, UUID issueId, UUID lineId, String fixType, String suggestionJson, BigDecimal confidence, String reason, Instant now){this.tenantId=tenantId;this.exceptionCaseId=caseId;this.validationRunId=runId;this.validationIssueId=issueId;this.extractedLineItemId=lineId;this.fixType=fixType;this.status="SUGGESTED";this.suggestionJson=suggestionJson==null?"{}":suggestionJson;this.confidence=confidence;this.reason=reason;this.createdAt=now;this.updatedAt=now;}
  public void setStatus(String status, Instant now){this.status=status;this.updatedAt=now;} public UUID getId(){return id;} public UUID getExceptionCaseId(){return exceptionCaseId;} public UUID getValidationRunId(){return validationRunId;} public UUID getValidationIssueId(){return validationIssueId;} public UUID getExtractedLineItemId(){return extractedLineItemId;} public String getFixType(){return fixType;} public String getStatus(){return status;} public String getSuggestionJson(){return suggestionJson;} public BigDecimal getConfidence(){return confidence;} public String getReason(){return reason;}
}
