package com.orderpilot.domain.bot;

/** OP-CAP-06B deterministic reason codes explaining a controlled flow policy decision. */
public enum BotFlowPolicyReason {
  BOT_DISABLED,
  FLOW_DISABLED,
  PRICE_VISIBILITY_NEVER,
  UNKNOWN_CUSTOMER_HANDOFF,
  UNKNOWN_CUSTOMER_REJECTED,
  AMBIGUOUS_CUSTOMER_HANDOFF,
  IDENTITY_BLOCKED,
  STALE_INVENTORY_HANDOFF,
  TENANT_POLICY_RESTRICTED,
  CONNECTION_NOT_ACTIVE,
  CONNECTION_NOT_VERIFIED,
  ALLOWED_CONTROLLED_DRAFT,
  ALLOWED_OPERATOR_REVIEW_ONLY,
  ALLOWED_CONTROLLED_RESPONSE
}
