package com.orderpilot.domain.bot;

public enum BotIntent {
  RFQ_REQUEST,
  PRODUCT_AVAILABILITY_QUESTION,
  PRICE_QUESTION,
  ORDER_STATUS_QUESTION,
  SUBSTITUTE_QUESTION,
  HUMAN_HELP_REQUEST,
  UNKNOWN
}
