package com.orderpilot.domain.bot;

public enum BotIntent {
  GREETING,
  CHECK_AVAILABILITY,
  CHECK_PRICE,
  REQUEST_QUOTE,
  SUGGEST_SUBSTITUTE,
  ORDER_OR_QUOTE_STATUS,
  HUMAN_HANDOFF,
  UNSUPPORTED_REQUEST_SAFE_REPLY,
  RFQ_REQUEST,
  PRODUCT_AVAILABILITY_QUESTION,
  PRICE_QUESTION,
  ORDER_STATUS_QUESTION,
  SUBSTITUTE_QUESTION,
  HUMAN_HELP_REQUEST,
  UNKNOWN
}
