package com.orderpilot.domain.bot;

public enum BotPolicyDecision {
  ALLOW_SAFE_RESPONSE,
  ALLOW_DRAFT_RESPONSE,
  REQUIRE_HUMAN_HANDOFF,
  BLOCK_UNSUPPORTED,
  REQUIRE_CUSTOMER_IDENTIFICATION,
  REQUIRE_OPERATOR_REVIEW
}
