package com.orderpilot.application.services.connector;

public enum DiagnosticCode {
  SECRET_MISSING,
  WEBHOOK_NOT_CONFIGURED,
  WEBHOOK_VERIFICATION_DISABLED,
  PROVIDER_UNREACHABLE,
  READ_ONLY_MODE,
  WRITE_MODE_NOT_ALLOWED,
  LAST_SYNC_FAILED,
  PERMISSION_INSUFFICIENT,
  TOKEN_EXPIRED,
  CONFIG_INVALID
}
